### ISSUE TITLE
zero

### ISSUE THREAD

**Issue by xffzero** [eslintisbad/1#1]
is better than one because fuck you that's why

**Comment by eslintisbad** [comment]
no u

**Comment by eslintisbad** [comment]
wait when did i make this repo

**Comment by eslintisbad** [comment]
oh yeah this is so i could get the thing to show up with the github copy+paste to clone and start

**Comment by eslintisbad** [comment]
fix the bug

**Comment by xffzero** [comment]
bin#0905

**Comment by eslintisbad** [comment]
you knew exactly what i wanted

baguette man

**Comment by eslintisbad** [comment]
dosmode
